config/routes.rb
Photogur::Application.routes.draw do

  resources :pictures

# post 'pictures/' => 'pictures#create' #add new part 2
# #this makes the index the homepage/root instead
# # of the "Rails" page

# get 'pictures' => 'pictures#index'

# get 'pictures/new' => 'pictures#new' #add new part 1


# get 'pictures/:id/edit' => 'pictures#edit', as: "edit_picture" #edit part 1
# # patch 'pictures/:id' => 'pictures#update' #edit part 2

# # delete 'pictures/:id' => 'pictures#destroy', as: "delete_picture"
 

# get 'pictures/:id' => 'pictures#show', as: "picture"

  root :to => 'pictures#index'


end

app/models/picture.rb
class Picture < ActiveRecord::Base

	def change 
		scope :newest_first, -> { order("created_at DESC")}
		scope :most_recent_five, -> { newest_first.limit(5)}
		scope :created_before, -> { where("created_at < ?", time)}	
	end
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@most_recent_pictures = Picture.most_recent_five
    # Picture refers to the Picture table under the model
    # @picture(s) is plural since it referes to all pictures 
    # held in the DB. plus since it contains multiple items
    # it is iterated over on index.html.erb 
	end

  def show
    @picture = Picture.find(params[:id].to_i)
  end

  def new
      @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
      if @picture.save
        redirect_to pictures_url
      else
        render :new #(:new refers to new.html.erb)
      end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
      if @picture.update_attributes(picture_params)
        redirect_to "/pictures/#{@picture.id}"
      else
        render :edit #(:edit refers to edit.html.erb) 
      end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

  private
  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edi Picture</h1>
<h3>url ‘/pictures/:id/edit'</h3>
<h4> folder: pictures -> resource: edit.html.erb (‘pictures#edit’)</h4>
<p>
	<%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
	<p>
		<%= f.label "artist" %><br>
		<%= f.text_field "artist" %>
	</p>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "url" %><br>
		<%= f.text_field "url" %>
	</p>
	<p> 
		<%= submit_tag "save" %>
	</p>
<%end%>

app/views/pictures/index.html.erb
<h1>Most Recent Pictures<h1>
<h3>url ‘pictures’ /</h3>
<h4> folder: pictures -> resource: index.html.erb (‘pictures#index’)</h4>
<%= link_to "New Picture", "pictures/new" %>

<ul>
<% @most_recent_pictures.each do |picture| %>
	<li><%= picture[:title] %></li>

	<% end %>
</ul>

app/views/pictures/new.html.erb
<h1>Add a Picture</h1>
<h3>url ‘/pictures/new'</h3>
<h4> folder: pictures -> resource: new.html.erb (‘pictures#new’)</h4>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f|%>
	<p>
		<%= f.label "artist" %><br>
		<%= f.text_field "artist" %>
	</p>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "url" %><br>
		<%= f.text_field "url" %>
	</p>
	<p>
		<%= f.submit "save" %>
	</p>
<% end %>

app/views/pictures/picture0.html.erb
<h1>Pictures<h1>
<h3>url ‘pictures /' 0</h3>
<h4> folder: pictures -> resource: picture0.html.erb (‘pictures#picture0’)</h4>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = <%= @picture[:url] %> >
	

app/views/pictures/picture1.html.erb
<h1>Pictures<h1>
<h3>url ‘pictures / 1'</h3>
<h4> folder: pictures -> resource: picture1.html.erb (‘pictures#picture1’)</h4>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = <%= @picture[:url] %> >
	

app/views/pictures/picture2.html.erb
<h1>Pictures<h1>
<h3>url ‘pictures / 2'</h3>
<h4> folder: pictures -> resource: picture2.html.erb (‘pictures#picture2’)</h4>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src = <%= @picture[:url] %> >
	

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", "/pictures" %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %>, <%= params[:id] %> </p>
<%= image_tag @picture.url %>